### ISSUE TITLE
Conflict with other before request middlewares

### ISSUE THREAD

**Issue by psiofxt** [dkruchinin/sanic-prometheus#15]
My error logs are getting filled with a 

```
line 62, in after_request_handler
    lat = time.time() - request['__START_TIME__']
KeyError: '__START_TIME__'
```
and I suspect it is some kind of conflict with `sanic-limiter` by bohea (https://github.com/bohea/sanic-limiter). When I disable my limiter `sanic-prometheus` handles fine. 

I can fork and try to patch this but I thought I'd bring it to your attention first to see if you've had any problem. 

Sample code to run with `sanic-limiter` and `sanic-prometheus` installed. Latest version of both from git (sanic-limiter is a bit out of date via pip). Run this and go to `localhost:8000/home` then try `localhost:8000/`. After going to an endpoint that will throw a 404 you'll see the prometheus error. 

```python
from sanic_prometheus import monitor
from sanic import Sanic, response, Blueprint
from sanic_limiter import Limiter, get_remote_address


app = Sanic()
test_bp = Blueprint('test')

limiter = Limiter(
    app,
    global_limits=['10 per second', '500 per day'],
    key_func=get_remote_address)


@test_bp.route('/home', methods=['GET'])
async def home(request):
    return response.json({'success': 'you are home'})


if __name__ == '__main__':
    monitor(app).expose_endpoint()
    app.blueprint(test_bp)
    app.run(host='127.0.0.1', port=8000, access_log=True)
```

**Comment by aviv-ebates** [comment]
+1
I think this is actually a design issue with Sanic itself - there's no way to control the order in which middlewares run, if any MW aborts, there's no guarantees about which MW actually ran.

As a workaround, we can just test in `after_request_handler:62` that `__START_TIME__` exists, and...? not report the call? report with null latency?

**Comment by dkruchinin** [comment]
@psiofxt 

Can't reproduce it with the latest version of `sanic-prometheus` from `HEAD`. What I see after hitting `localhost:8000/` is
```
[2019-01-25 16:07:46 +0000] [12111] [ERROR] Exception occurred while handling uri: 'http://localhost:8000/'
Traceback (most recent call last):
  File "/Users/dk/.virtualenvs/sanic/lib/python3.7/site-packages/sanic/app.py", line 736, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/Users/dk/.virtualenvs/sanic/lib/python3.7/site-packages/sanic/router.py", line 396, in get
    return self._get(request.path, request.method, "")
  File "/Users/dk/.virtualenvs/sanic/lib/python3.7/site-packages/sanic/router.py", line 458, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
[2019-01-25 16:07:46 +0000] - (sanic.access)[INFO][127.0.0.1:62583]: GET http://localhost:8000/  404 32
[2019-01-25 16:07:51 +0000] [12111] [DEBUG] KeepAlive Timeout. Closing connection.
[2019-01-25 16:08:29 +0000] - (sanic.access)[INFO][127.0.0.1:62585]: GET http://localhost:8000/metrics  200 3979
[2019-01-25 16:08:34 +0000] [12111] [DEBUG] KeepAlive Timeout. Closing connection.
```

Sanic version: `sanic==18.12.0`.
Please let me know if you're still seeing this problem. 🙏
